name: test

on:
  push:
    branches:
      - refactor/c2cpp

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl libssl-dev 
      - name: Run test
        run: |
          cd src/test
          make
          ./main
